name: Populate NDAWN Coordinates

on:
  workflow_dispatch:

jobs:
  populate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install packages
      run: |
        pip install pandas requests beautifulsoup4 openpyxl

    - name: Run script
      run: |
        python ND_coords_populate.py

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: ND-Coordinates
        path: ND_coords_populated.xlsx
