name: Update Weather

on:
  workflow_dispatch:
  schedule:
    - cron: '*/11 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Repository
       uses: actions/checkout@v4

     - name: Setup Python
       uses: actions/setup-python@v5
       with:
        python-version: '3.12'

     - name: Run Weather Script
       run: python update_weather.py

     - name: Commit Files
       run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add currentwx.txt weather.csv
          git commit -m "Weather update" || echo "No changes"
          git pull --rebase origin main
          git push
